#USB摄像头图像获取及处理软件

#刘阳
#摄像头参数设置对话框的UI文件

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog

class Ui_setDialog(object):
    def setupUi(self,setDialog,
                PropertyValue={'bright':0,'contrast':10,'saturation':5,'hue':0,'sharpness':5,'gamma':150,'gain':40},
                PropertyRange={'brimin':-10,'brimax':10,'conmin':0,'conmax':20,'satmin':0,'satmax':10,
                'huemin':-5,'huemax':5,'shamin':0,'shamax':10,'gammin':100,'gammax':200,'gaimin':32,'gaimax':48}):
        self.bri=PropertyValue['bright']
        self.con=PropertyValue['contrast']
        self.sat=PropertyValue['saturation']
        self.hue=PropertyValue['hue']
        self.sha=PropertyValue['sharpness']
        self.gam=PropertyValue['gamma']
        self.gai=PropertyValue['gain']
        setDialog.setObjectName("setDialog")
        setDialog.resize(320, 280)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.widget = QtWidgets.QWidget(setDialog)
        self.widget.setGeometry(QtCore.QRect(22, 22, 271, 231))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Hue = QtWidgets.QSlider(self.widget)
        self.Hue.setMinimum(PropertyRange['huemin'])
        self.Hue.setMaximum(PropertyRange['huemax'])
        self.Hue.setValue(self.hue)
        self.Hue.setOrientation(QtCore.Qt.Horizontal)
        self.Hue.setObjectName("Hue")
        self.gridLayout.addWidget(self.Hue, 3, 1, 1, 1)
        self.labelGam = QtWidgets.QLabel(self.widget)
        self.labelGam.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelGam.setObjectName("labelGam")
        self.gridLayout.addWidget(self.labelGam, 6, 0, 1, 1)
        self.Saturation = QtWidgets.QSlider(self.widget)
        self.Saturation.setMaximum(PropertyRange['satmax'])
        self.Saturation.setMinimum(PropertyRange['satmin'])
        self.Saturation.setProperty("value",self.sat)
        self.Saturation.setOrientation(QtCore.Qt.Horizontal)
        self.Saturation.setObjectName("Saturation")
        self.gridLayout.addWidget(self.Saturation, 2, 1, 1, 1)
        self.labelHue = QtWidgets.QLabel(self.widget)
        self.labelHue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelHue.setObjectName("labelHue")
        self.gridLayout.addWidget(self.labelHue, 3, 0, 1, 1)
        self.Brightness = QtWidgets.QSlider(self.widget)
        self.Brightness.setMinimum(PropertyRange['brimin'])
        self.Brightness.setMaximum(PropertyRange['brimax'])
        self.Brightness.setProperty("value", self.bri)
        self.Brightness.setOrientation(QtCore.Qt.Horizontal)
        self.Brightness.setObjectName("Brightness")
        self.gridLayout.addWidget(self.Brightness, 0, 1, 1, 1)
        self.labelGai = QtWidgets.QLabel(self.widget)
        self.labelGai.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelGai.setObjectName("labelGai")
        self.gridLayout.addWidget(self.labelGai, 5, 0, 1, 1)
        self.Gain = QtWidgets.QSlider(self.widget)
        self.Gain.setMinimum(PropertyRange['gaimin'])
        self.Gain.setMaximum(PropertyRange['gaimax'])
        self.Gain.setProperty("value",self.gai)
        self.Gain.setOrientation(QtCore.Qt.Horizontal)
        self.Gain.setObjectName("Gain")
        self.gridLayout.addWidget(self.Gain, 5, 1, 1, 1)
        self.labelBri = QtWidgets.QLabel(self.widget)
        self.labelBri.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelBri.setObjectName("labelBri")
        self.gridLayout.addWidget(self.labelBri, 0, 0, 1, 1)
        self.labelConVal = QtWidgets.QLabel(self.widget)
        self.labelConVal.setMinimumSize(QtCore.QSize(25, 25))
        self.labelConVal.setObjectName("labelConVal")
        self.gridLayout.addWidget(self.labelConVal, 1, 2, 1, 1)
        self.labelShaVal = QtWidgets.QLabel(self.widget)
        self.labelShaVal.setMinimumSize(QtCore.QSize(25, 25))
        self.labelShaVal.setObjectName("labelShaVal")
        self.gridLayout.addWidget(self.labelShaVal, 4, 2, 1, 1)
        self.Sharpness = QtWidgets.QSlider(self.widget)
        self.Sharpness.setMinimum(PropertyRange['shamin'])
        self.Sharpness.setMaximum(PropertyRange['shamax'])
        self.Sharpness.setProperty("value",self.sha)
        self.Sharpness.setOrientation(QtCore.Qt.Horizontal)
        self.Sharpness.setObjectName("Sharpness")
        self.gridLayout.addWidget(self.Sharpness, 4, 1, 1, 1)
        self.labelBriVal = QtWidgets.QLabel(self.widget)
        self.labelBriVal.setMinimumSize(QtCore.QSize(25, 25))
        self.labelBriVal.setObjectName("labelBriVal")
        self.gridLayout.addWidget(self.labelBriVal, 0, 2, 1, 1)
        self.labelSatVal = QtWidgets.QLabel(self.widget)
        self.labelSatVal.setMinimumSize(QtCore.QSize(25, 25))
        self.labelSatVal.setObjectName("labelSatVal")
        self.gridLayout.addWidget(self.labelSatVal, 2, 2, 1, 1)
        self.labelGamVal = QtWidgets.QLabel(self.widget)
        self.labelGamVal.setMinimumSize(QtCore.QSize(25, 25))
        self.labelGamVal.setObjectName("labelGamVal")
        self.gridLayout.addWidget(self.labelGamVal, 6, 2, 1, 1)
        self.labelSha = QtWidgets.QLabel(self.widget)
        self.labelSha.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelSha.setObjectName("labelSha")
        self.gridLayout.addWidget(self.labelSha, 4, 0, 1, 1)
        self.Contrast = QtWidgets.QSlider(self.widget)
        self.Contrast.setMinimum(PropertyRange['conmin'])
        self.Contrast.setMaximum(PropertyRange['conmax'])
        self.Contrast.setProperty("value", self.con)
        self.Contrast.setOrientation(QtCore.Qt.Horizontal)
        self.Contrast.setObjectName("Contrast")
        self.gridLayout.addWidget(self.Contrast, 1, 1, 1, 1)
        self.labelCon = QtWidgets.QLabel(self.widget)
        self.labelCon.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCon.setObjectName("labelCon")
        self.gridLayout.addWidget(self.labelCon, 1, 0, 1, 1)
        self.labelSat = QtWidgets.QLabel(self.widget)
        self.labelSat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelSat.setObjectName("labelSat")
        self.gridLayout.addWidget(self.labelSat, 2, 0, 1, 1)
        self.labelHueVal = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHueVal.sizePolicy().hasHeightForWidth())
        self.labelHueVal.setSizePolicy(sizePolicy)
        self.labelHueVal.setMinimumSize(QtCore.QSize(25, 25))
        self.labelHueVal.setObjectName("labelHueVal")
        self.gridLayout.addWidget(self.labelHueVal, 3, 2, 1, 1)
        self.Gamma = QtWidgets.QSlider(self.widget)
        self.Gamma.setMinimum(PropertyRange['gammin'])
        self.Gamma.setMaximum(PropertyRange['gammax'])
        self.Gamma.setSingleStep(1)
        self.Gamma.setProperty("value", self.gam)
        self.Gamma.setOrientation(QtCore.Qt.Horizontal)
        self.Gamma.setObjectName("Gamma")
        self.gridLayout.addWidget(self.Gamma, 6, 1, 1, 1)
        self.labelGaiVal = QtWidgets.QLabel(self.widget)
        self.labelGaiVal.setMinimumSize(QtCore.QSize(25, 25))
        self.labelGaiVal.setObjectName("labelGaiVal")
        self.gridLayout.addWidget(self.labelGaiVal, 5, 2, 1, 1)

        self.retranslateUi(setDialog)
        self.Brightness.valueChanged['int'].connect(self.labelBriVal.setNum)
        self.Contrast.valueChanged['int'].connect(self.labelConVal.setNum)
        self.Saturation.valueChanged['int'].connect(self.labelSatVal.setNum)
        self.Hue.valueChanged['int'].connect(self.labelHueVal.setNum)
        self.Sharpness.valueChanged['int'].connect(self.labelShaVal.setNum)
        self.Gain.valueChanged['int'].connect(self.labelGaiVal.setNum)
        self.Gamma.valueChanged['int'].connect(self.labelGamVal.setNum)
        QtCore.QMetaObject.connectSlotsByName(setDialog)

        if(PropertyRange['brimin']==PropertyRange['brimax']):
            self.labelBriVal.setText("——")
            self.Brightness.setEnabled(False)
        if(PropertyRange['conmin']==PropertyRange['conmax']):
            self.labelConVal.setText("——")
            self.Contrast.setEnabled(False)
        if(PropertyRange['satmin']==PropertyRange['satmax']):
            self.labelSatVal.setText("——")
            self.Saturation.setEnabled(False)
        if(PropertyRange['huemin']==PropertyRange['huemax']):
            self.labelHueVal.setText("——")
            self.Hue.setEnabled(False)
        if(PropertyRange['shamin']==PropertyRange['shamax']):
            self.labelShaVal.setText("——")
            self.Sharpness.setEnabled(False)
        if(PropertyRange['gammin']==PropertyRange['gammax']):
            self.labelGamVal.setText("——")
            self.Gamma.setEnabled(False)
        if(PropertyRange['gaimin']==PropertyRange['gaimax']):
            self.labelGaiVal.setText("——")
            self.Gain.setEnabled(False)
        
    def retranslateUi(self, setDialog):
        _translate = QtCore.QCoreApplication.translate
        setDialog.setWindowTitle(_translate("setDialog", "摄像头参数设置"))
        self.labelGam.setText(_translate("setDialog", "灰度系数"))
        self.labelHue.setText(_translate("setDialog", "色调值"))
        self.labelGai.setText(_translate("setDialog", "增益值"))
        self.labelBri.setText(_translate("setDialog", "亮度值"))
        self.labelConVal.setText(_translate("setDialog", str(self.con)))
        self.labelShaVal.setText(_translate("setDialog", str(self.sha)))
        self.labelBriVal.setText(_translate("setDialog", str(self.bri)))
        self.labelSatVal.setText(_translate("setDialog", str(self.sat)))
        self.labelGamVal.setText(_translate("setDialog", str(self.gam)))
        self.labelSha.setText(_translate("setDialog", "锐度值"))
        self.labelCon.setText(_translate("setDialog", "对比度"))
        self.labelSat.setText(_translate("setDialog", "饱和度"))
        self.labelHueVal.setText(_translate("setDialog", str(self.hue)))
        self.labelGaiVal.setText(_translate("setDialog", str(self.gai)))

class PropertyDialog(QDialog,Ui_setDialog):             #摄像头参数调节类
    def __init__(self,parent=None):
        super(PropertyDialog,self).__init__(parent)
